In [12]:
import numpy
mylist = [[19, 29, 39], [39, 49, 59]]
myarray = numpy.array(mylist)
print(myarray)
print(myarray.shape)


[[19 29 39]
 [39 49 59]]
(2, 3)


In [16]:
myarray[[1],[1,2]]

array([49, 59])

In [4]:
import numpy
import pandas
myarray = numpy.array([18, 28, 38])
rownames = ['aa', 'ba', 'cc']
myseries = pandas.Series(myarray, index=rownames)
print(myseries)

aa    18
ba    28
cc    38
dtype: int32


In [5]:
# dataframe
import numpy
import pandas
myarray = numpy.array([[15, 25, 35], [45, 55, 65]])
rownames = ['aa', 'ab']
colnames = ['one', 'two', 'three']
mydataframe = pandas.DataFrame(myarray, index=rownames, columns=colnames)
#print(mydataframe)
mydataframe

one  two  three
aa   15   25     35
ab   45   55     65

In [ ]:
# Create df from dictionary
sales = [{'account': 'Shnkr', 'M-1': 150, 'M-2': 200, 'M-3': 140},
         {'account': 'Saurav',  'M-1': 200, 'M-2': 210, 'M-3': 215},
         {'account': 'Binay',  'M-1': 50,  'M-2': 90,  'M-3': 95 }]
import pandas as pd
df = pd.DataFrame(sales)
df

In [ ]:
s={'account':['Shnkr','Saurav','Binay'],
  'M-1':[150,200,50],
  'M-2':[200,150,100]}
d=pandas.DataFrame(s,index=list('abc'))
d

In [ ]:
l1=['p','q','r'];l1

In [ ]:
l2=list('pqr');l2

In [ ]:
l3='p,qp,r'
l3

In [ ]:
l3.split(',')

In [ ]:
# re-sequence manually
df = df[['account', 'M-1', 'M-2', 'M-3']]
df

In [ ]:
range(10)

In [ ]:
list(range(10))

In [ ]:
list(range(3,20,3))

In [ ]:
list(range(-10,10,2))*2

In [17]:
import numpy as np
l3=np.array(list(range(-10,10,2)))
type(l3)

numpy.ndarray

In [18]:
l3*2

array([-20, -16, -12,  -8,  -4,   0,   4,   8,  12,  16])

In [19]:
np.log(l3)

C:\Users\pd147\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
C:\Users\pd147\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan,        nan,        nan,
             -inf, 0.69314718, 1.38629436, 1.79175947, 2.07944154])

In [20]:
np.log(np.abs(l3))

C:\Users\pd147\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([2.30258509, 2.07944154, 1.79175947, 1.38629436, 0.69314718,
             -inf, 0.69314718, 1.38629436, 1.79175947, 2.07944154])

In [ ]:
np.log?


In [21]:
np.exp(l3)

array([4.53999298e-05, 3.35462628e-04, 2.47875218e-03, 1.83156389e-02,
       1.35335283e-01, 1.00000000e+00, 7.38905610e+00, 5.45981500e+01,
       4.03428793e+02, 2.98095799e+03])

In [ ]:
np.angle?

In [ ]:
l4=np.arange(-10,10,2)
l4

In [22]:
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [ ]:
#If-Then-Else Conditional (space/tab is important!)
value1 = 5555
if value1 == 995:
    print('Correct!')
elif value1 > 2005:
    print('Large')
else:
    print ('Small')

In [ ]:
#If-Then-Else Conditional (space/tab is important!)
value1 = float(input('Enter Number: '))
if value1 == 995:
    print('Correct!')
elif value1 > 2005:
    print('Large')
else:
    print ('Small')

In [ ]:
[2*i for i in range(1,6)]

In [ ]:
var=input()
l=[float(x) for x in var.split(',')]
np.mean(l)

In [ ]:
# For-Loop
for i in range(25):
    print(i)

In [ ]:
# While-Loop
i = 0
while i < 50:
    print(i)
    i += 1

In [1]:
# Sum function
def mysum(x, y):
    return (x + y)

In [2]:
mysum(3,4)

7

In [ ]:
import numpy as np
np.random.seed(0)
np.random.random(6)